apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: git-server
spec:
  replicas: 1
  serviceName: git-svc
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
      - name: git-server
        image: 352708296901.dkr.ecr.us-east-2.amazonaws.com/git-server:0.0.1
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/srv"
            name: git-server-data
        resources:
          requests:
            cpu: "10m"
            memory: 50Mi
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: git-server-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: gp2
        resources:
          requests:
            storage: 5Gi
  selector:
    matchLabels:
      app: git-server
